"""Run report schema for scenario execution results."""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, ConfigDict


class RunReport(BaseModel):
    """Structured report produced by a scenario run."""

    scenario_path: str = Field(..., description="Path to scenario YAML file")
    fitted_params: Optional[Dict[str, Any]] = Field(
        default=None, description="Model parameters fitted during the run"
    )
    metrics: Dict[str, float] = Field(
        default_factory=dict, description="Computed metrics keyed by name"
    )
    artifacts: List[str] = Field(
        default_factory=list, description="Artifact file paths generated by the run"
    )
    narrative: Optional[str] = Field(
        default=None, description="Optional human-readable explanation"
    )

    model_config = ConfigDict(extra="forbid")
